### ISSUE TITLE
`registerVideo`にniconicoのソース追加

### ISSUE THREAD

**Issue by SnO2WMaN** [otomad-database/api#3]
```graphql
input RegisterVideoInput {
  primaryTitle: String!
  extraTitles: [String!]
  tags: [ID!]!
  primaryThumbnail: String!
  niconico: [String!] # 追加
}
```

URLが突っ込まれる

**Comment by naari3** [comment]
後からyoutubeとかtwitterとかが追加される想定？コンテキスト違ったら申し訳ないですが、一括してurlで丸めるという話があったような気が……

**Comment by SnO2WMaN** [comment]
URLというよりniconicoの動画IDを入れて**niconicoの動画に対して**重複がないかとか音MADタグ付いているかとかを検証する予定

**Comment by naari3** [comment]
とすると、今後(ミニマルな実装以後)は別のサービス向けにも同じようにフィールドが実装される想定？将来的にはotomad databaseが対応したサービスの場合のみ(URLの一致とかではなくて)もう少しリッチな検証が行われるものだと認識しました

**Comment by SnO2WMaN** [comment]
基本的にそうですね（多分個人サイトみたいな場所でこじんまりと音MAD出している例とかはさすがに無いと思うので…（あるのか？））
