### ISSUE TITLE
`ResolverArgs`の型推論が間違っている

### ISSUE THREAD

**Issue by SnO2WMaN** [otomad-database/api#39]
`utils/types.ts`の`ResolverArgs`が全然間違っているらしく，第一引数に`TParent`が来ることになっているが，実際には来ない（第一引数にやってくるのは`TArgs`）

**Comment by SnO2WMaN** [comment]
codegenの生成がそもそもおかしい

**Comment by SnO2WMaN** [comment]
`Video.hasTag`が延々と嘘を返し続けている（`input`が正しく取得できていないので）

**Comment by rokoucha** [comment]
やっぱそうかー、codegen と graphql.js の型が当ってない可能性は codegen 入れる時にちょっと思ってたけど見なかった事にしてた

**Comment by rinsuki** [comment]
https://the-guild.dev/graphql/codegen/docs/guides/graphql-server-apollo-yoga apollo server 用？

**Comment by rinsuki** [comment]
確かに第一引数にオプション来そう https://graphql.org/graphql-js/object-types/

**Comment by rinsuki** [comment]
いやこれやると合ってる直resolversのほうも変わっちゃうな

**Comment by SnO2WMaN** [comment]
我々は全員間違えていて，すべき実装は以下だった．

```
{
  Query: {},
  Mutation: {},
  Video: {
    hasTag(parent,args,ctx,info) {
      console.dir(parent);
      return false;
    },
  },
};
```

**Comment by SnO2WMaN** [comment]
多分もう解決しただろう
